	name:	echo;
    lcmd:	echo;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
---
	name:	pwd;
    lcmd:	pwd;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
---
	name:	clear;
    lcmd:	clear;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
---