name: tail;
lcmd: tail -f /tmp/toto;
pcount: 1;
autostart: FALSE;
rstart_cond: FALSE;
exitcodes: 0,1;
startwait: 0;
retry: 3;
exitsig: 3;
killwait: 0;
pid_logging: TRUE;
pid_logfile: NULL;
env_vars: array();
wrk_dir: NULL;
umask: 0;
---