name: a.out;
lcmd: ./a.out;
pcount: 1;
autostart: TRUE;
rstart_cond: TRUE;
exitcodes: 0,1;
startwait: 2;
retry: 3;
exitsig: 3;
killwait: 0;
pid_logging: TRUE;
pid_logfile: aout.txt;
env_vars: path=/tmp/toto,env=value;
wrk_dir: /tmp;
umask: 077;
---
name: tail;
lcmd: tail -f /tmp/toto;
pcount: 1;
autostart: TRUE;
rstart_cond: TRUE;
exitcodes: 0,1;
startwait: 2;
retry: 3;
exitsig: 3;
killwait: 0;
pid_logging: TRUE;
pid_logfile: exampleOut.txt;
env_vars: path=/tmp/toto,env=value;
wrk_dir: /tmp;
umask: 077;
---