ls:
    pid:	false;
    lcmd:	false;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
    status:	false;
    restartMe:	false;
    child:	false;
    name:	false;
---
echo:
    pid:	false;
    lcmd:	false;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
    status:	false;
    restartMe:	false;
    child:	false;
    name:	false;
---
pwd:
    pid:	false;
    lcmd:	false;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
    status:	false;
    restartMe:	false;
    child:	false;
    name:	false;
---
clear:
    pid:	false;
    lcmd:	false;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
    status:	false;
    restartMe:	false;
    child:	false;
    name:	false;
---