	name:	ls;
    pid:	false;
    lcmd:	false;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
    status:	false;
    restartMe:	false;
    child:	false;
---
	name:	echo;
    pid:	f234235;
    lcmd:	false;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
    status:	false;
    restartMe:	false;
    child:	false;
---
	name:	pwd;
    pid:	523532;
    lcmd:	false;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
    status:	false;
    restartMe:	false;
    child:	false;
---
	name:	clear;
    pid:	23523;
    lcmd:	false;
    pcount:	false;
    autostart:	false;
    rstart_cond:	false;
    exitcodes:	false;
    startwait:	false;
    retry:	false;
    exitsig:	false;
    killwait:	false;
    pid_logging:	false;
    pid_logfile:	false;
    env_vars:	false;
    wrk_dir:	false;
    umask:	false;
    status:	false;
    restartMe:	false;
    child:	false;
---